### ISSUE TITLE
No module named 'hydro_raster.Raster'; 'hydro_raster' is not a package

### ISSUE THREAD

**Issue by weiyilan** [mingxiaodong/hydro-raster#3]
Hiiii, I have successfully installed hydro_raster however, when I run 'from hydro_raster.Raster import Raster', it says "ModuleNotFoundError: No module named 'hydro_raster.Raster'; 'hydro_raster' is not a package"
![捕获](https://github.com/mingxiaodong/hydro-raster/assets/43534645/e4a4bcb0-a6f5-418d-93e9-45047ddc8630)

**Comment by xiaxilin** [comment]
Hi, I tried it on Google Colab with the following code, there doesn't seem to be any issue. I was using the following

```Python
from hydro_raster.Raster import Raster
from hydro_raster import get_sample_data
tif_file_name = get_sample_data('tif')
ras_obj = Raster(tif_file_name)
```

Maybe it something to do with your conda environment set up?
